<div>
        <embed
            src="{{asset('http://192.168.128.193:8080/'.$doc['pathfile'])}}"
            type="application/pdf"
            frameBorder="0"
            scrolling="auto"
            height="1080px"
            width="100%"
        ></embed>        
</div>
